
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: auto-frontend:latest
    container_name: auto_frontend
    ports:
      - "80:80"  
    restart: unless-stopped
  
