services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: auto-frontend:latest
    container_name: auto_frontend
    ports:
      - "80:80"
      - "443:443"                
    restart: unless-stopped
    volumes:
      - certbot-www:/var/www/certbot        
      - letsencrypt:/etc/letsencrypt:ro     

  certbot:
    image: certbot/certbot:latest
    container_name: auto_certbot
    depends_on:
      - frontend
    volumes:
      - certbot-www:/var/www/certbot       
      - letsencrypt:/etc/letsencrypt       

volumes:
  certbot-www:
  letsencrypt:
